name: Lint and Test

on: [push]

jobs:
  lint:
    name: Lint and Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run 'prettier' code formatter
        run: yarn format:check

      - name: Run 'eslint' code linter
        run: yarn lint